### ISSUE TITLE
Feature Request: Alternate line color in feeds

### ISSUE THREAD

**Issue by jt4703** [brief-rss/brief#382]
I'd like to have an alternating line color effect in the feed headline view. I attempted to do this by modifying the headline header background for the nth-child (odd) and nth-child (even) and with tr in front and not but no luck. I settled for getting all of the backgrounds to grey and making the text pure black with a border around each item, but I'd like the alternate color to be a lighter grey or a light blue instead. How do I target alternate rows to give them the other color? 
This is my current customization code:

.headline-header  {
  border:1px solid #526169;
  background-color: #EFEFEF!important; 
}

.headline-title{
    color: black !important;
}

**Comment by rhendric** [comment]
Try this?
```css
.headlines-view > #feed-content article:nth-of-type(even) .headline-header {
    background-color: aliceblue;
}
```
