### ISSUE TITLE
dark theme example

### ISSUE THREAD

**Issue by atomGit** [brief-rss/brief#556]
this is a **very quick and dirty** hack of a dark theme - i may improve it over time if i continue to use brief

<details>
<summary>click</summary>

```css
html {
    background: #000 !important;
}

/* SIDEBAR */
#sidebar-splitter,
#tag-list-splitter {
    border-left: 3px solid #626262 !important;
    border-right: unset !important;
}
#sidebar {
    background-color: #2b2b2b !important;
}
.sidebar-button {
    color: #ff6800 !important;
}
#sidebar-top {
    border-bottom: 3px solid #626262 !important;
}
#view-list {
    background-color: #353535 !important;
    padding-bottom: 10px !important;
}
#view-list > tree-item > .title {
    color: unset !important;
}
tree-box {
    border-bottom: 3px solid #626262 !important;
}
tree-folder {
    margin: 5px 0 5px 8px !important;
}
tree-folder-header {
    padding: 0 !important;
    border: none !important;
}
tree-folder-header > .toggle-collapsed {
    opacity: 0.4;
}
tree-folder-header > .toggle-collapsed {
    opacity: 1;
}
tree-folder:not(.selected) > tree-folder-header:hover {
    background-color: #455b76 !important;
    border-color: #2b2b2b !important;
}
tree-item {
    padding: unset !important;
}
tree-item:hover:not(.selected),
tree-item > .title,
tree-folder-header > .title,
tree-folder-footer > .title {
    color: unset !important;
}
tree-item.selected,
tree-folder.selected > tree-folder-header {
    background-color: #455b76 !important;
    border: none !important;
}
tree-item > .icon,
tree-item > .system-icon {
    border: 1px solid #a2a2a2 !important;
}

/* ARTICLES PANE HEADER */
#feed-view-header {
    background: #2b2b2b !important;
}
#view-title-label {
color: #ff6800 !important;
}
.controls {
    background: #000;
}
#searchbar {
    color: unset !important;
}

/* ARTICLES PANE */
body {
    background: #2b2b2b;
}
#feed-content .full-container {
    flex: 0 1 90% !important;
    max-width: 1200px !important;
}
.headline-container {
    flex: auto !important;
    overflow: visible !important;
    flex: 0 1 90% !important;
    max-width: 1200px !important;
    white-space: wrap !important;
    color: #a4a4a4 !important;
}
.headline-container:hover > .headline-header {
    background-color: #4a4a4a !important;
}
.headline-feed-name {
    height: unset !important;
}
.day-header {
    background: #bd1d1d !important;
    padding: 10px 0 10px 20px !important;
    font-weight: bold;
}
.headline-title {
    height: unset;
    white-space: wrap;
    overflow: visible;
    color: #deddda;
}
.full-container-inner {
    border: none !important;
    background: none !important;
}
.title-link {
    color: #bfbfbf;
    overflow: visible;
}
.content a {
    color: #ff6800;
}
.content {
    color: #deddda !important;
    text-align: unset !important;
}
```

</details>
