### ISSUE TITLE
Feed properties -> filter

### ISSUE THREAD

**Issue by tophf** [brief-rss/brief#86]
Could be useful: an option in the feed properties to fetch only the articles that:
(*) contain specified comma delimited list of words or [x] regexp
( ) don't contain specified comma delimited list of words or [x] regexp

**Comment by slrslr** [comment]
7 years later, I agree. Would like to set certain feed option to list only items which title or description contains certain phrase/s. Seems like basic and important feature.

**Comment by lostthing** [comment]
Since this function may not available in a short time, I'm using custom CSS in settings to highlight any article if title contains specific words, but it works in headline view only:
```css
*[title*="keyword1"], *[title*="keyword2"], *[title*="keyword3"] { background-color: rgb(176, 52, 14) !important;}
```
